# streamlit_app.py: Simple web-based user interface for the PDF chatbot using Streamlit
# The UI allows users to ask questions about a PDF document and get answers generated by a local LLM (via Ollama) - combined with RAG.
import os
os.environ["TORCH_DISABLE_SOURCE_WATCHER"] = "1"
os.environ["STREAMLIT_SERVER_FILE_WATCHER_TYPE"] = "none"

import streamlit as st
from chatbot_core import build_qa_chain

st.set_page_config(page_title="📄 PDF-Chatbot", layout="wide")
st.title("📄 Chat with your PDF")

qa_chain = build_qa_chain("ucf_rules.pdf")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []  

question = st.text_input("What would you like to know?", key="input")

if question:
    result = qa_chain.invoke({
        "question": question,
        "chat_history": st.session_state.chat_history
    })

    st.session_state.chat_history.append((question, result["answer"]))

    for i, (q, a) in enumerate(st.session_state.chat_history[::-1]):
        st.markdown(f"**❓ Question {len(st.session_state.chat_history) - i}:** {q}")
        st.markdown(f"**🤖 Answer:** {a}")